---

- hosts: webservers
  become: yes
  remote_user: ubuntu
  tasks:
    - name: install updates
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
    
    - name: Install apache and php
      apt: 
        name:
          - apache2
          - libapache2-mod-php
        state: latest

    - name: Start apache service
      service: 
        name: apache2
        state: started

    - name: Set timezone to africa/lagos
      timezone: 
        name: Africa/Lagos

    
    - name: Delete content & directory
      file:
        state: absent
        path: /var/www/html/index.html

    - name: Set up Php index page
      ansible.builtin.copy:
        src:  ./files/index.php
        dest: /var/www/html/index.php
      
      
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted